/* GENERATED by scripts/tts-generate.mjs — do not edit by hand.
 *
 * One entry per line of the call simulator, synthesised with Telenow's own
 * voices at tts.telenow.ai. Re-run the script to refresh:
 *
 *   node scripts/tts-generate.mjs --force
 */

export const CLIPS: Record<string, string> = {
  'call:CX-8841:0': '/audio/CX-8841-00.mp3',
  'call:CX-8841:1': '/audio/CX-8841-01.mp3',
  'call:CX-8841:2': '/audio/CX-8841-02.mp3',
  'call:CX-8841:3': '/audio/CX-8841-03.mp3',
  'call:CX-8841:4': '/audio/CX-8841-04.mp3',
  'call:CX-8841:5': '/audio/CX-8841-05.mp3',
  'call:CX-8841:6': '/audio/CX-8841-06.mp3',
  'call:CX-8841:7': '/audio/CX-8841-07.mp3',
  'call:CX-8841:8': '/audio/CX-8841-08.mp3',
  'call:CX-9014:0': '/audio/CX-9014-00.mp3',
  'call:CX-9014:1': '/audio/CX-9014-01.mp3',
  'call:CX-9014:2': '/audio/CX-9014-02.mp3',
  'call:CX-9014:3': '/audio/CX-9014-03.mp3',
  'call:CX-9014:4': '/audio/CX-9014-04.mp3',
  'call:CX-9014:5': '/audio/CX-9014-05.mp3',
  'call:CX-9014:6': '/audio/CX-9014-06.mp3',
  'call:CX-9014:7': '/audio/CX-9014-07.mp3',
  'call:CX-9014:8': '/audio/CX-9014-08.mp3',
  'call:CX-9188:0': '/audio/CX-9188-00.mp3',
  'call:CX-9188:1': '/audio/CX-9188-01.mp3',
  'call:CX-9188:2': '/audio/CX-9188-02.mp3',
  'call:CX-9188:3': '/audio/CX-9188-03.mp3',
  'call:CX-9188:4': '/audio/CX-9188-04.mp3',
  'call:CX-9188:5': '/audio/CX-9188-05.mp3',
  'call:CX-9188:6': '/audio/CX-9188-06.mp3',
  'call:CX-9188:7': '/audio/CX-9188-07.mp3',
  'call:CX-9188:8': '/audio/CX-9188-08.mp3',
  'call:CX-9302:0': '/audio/CX-9302-00.mp3',
  'call:CX-9302:1': '/audio/CX-9302-01.mp3',
  'call:CX-9302:2': '/audio/CX-9302-02.mp3',
  'call:CX-9302:3': '/audio/CX-9302-03.mp3',
  'call:CX-9302:4': '/audio/CX-9302-04.mp3',
  'call:CX-9302:5': '/audio/CX-9302-05.mp3',
  'call:CX-9302:6': '/audio/CX-9302-06.mp3',
  'call:CX-9455:0': '/audio/CX-9455-00.mp3',
  'call:CX-9455:1': '/audio/CX-9455-01.mp3',
  'call:CX-9455:2': '/audio/CX-9455-02.mp3',
  'call:CX-9455:3': '/audio/CX-9455-03.mp3',
  'call:CX-9455:4': '/audio/CX-9455-04.mp3',
  'call:CX-9455:5': '/audio/CX-9455-05.mp3',
  'call:CX-9455:6': '/audio/CX-9455-06.mp3',
}
